Add RAI type conversion functions
scijava/incubator pull request #103
Opened 2023-12-13 21:09 UTC by gselzer

Since this is a very heavily used function, I'd like to avoid the adaptation system, because it has a *lot* of trouble with a function with an any output.

I also refactored the "image.fill" Ops for better performance and less boilerplate

Closes scijava/scijava#167

2023-12-16 20:02 UTC, hinerm requested changes
This currently is not compiling with errors like
```
 error: <T,RAIT>typeToUnsigned2Bit(java.util.function.BiFunction<net.imglib2.Dimensions,net.imglib2.type.numeric.integer.Unsigned2BitType,net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.integer.Unsigned2BitType>>,org.scijava.function.Computers.Arity1<T,net.imglib2.type.numeric.integer.Unsigned2BitType>,RAIT) has a return, but no @return parameter
```

I tried splitting out the return parsing changes but that was not sufficient. I'll be happy to look at it on Monday.

2023-12-16 20:28 UTC, gselzer commented
@hinerm did you pre-build the annotation processor?

`mvn clean install -pl scijava/scijava-ops-indexer -am && mvn clean install`, from memory, is the needed command

2023-12-18 16:10 UTC, hinerm commented
> @hinerm did you pre-build the annotation processor?

Yes I did

2023-12-18 18:20 UTC, hinerm approved these changes

2023-12-18 18:20 UTC, merged