Op Reduction, Rebased
scijava/incubator pull request #58
Opened 2022-03-24 18:47 UTC by gselzer

This PR rebases the work of #32 on top of #57, making it much easier to merge.

Please see #32 for a description of the workings.

2022-09-07 22:28 UTC, ctrueden commented
@gselzer I tried to get started on this PR by:
```
gh pr checkout 58
git reset --hard main
git cherry-pick eaf3fe75d938c14326f4f94fe027e97ec33d7ad2
```
because I think the only commit that is actually new here is the tip.

But there are conflicts. I'll take another crack at it next week. Once I resolve the conflicts, my next steps will be:

1. Verify that everything still actually works.
2. Rewrite the commit message to include all the good details written up in #32.
3. Review the actual patch, commenting on things we should follow up on later.
4. Merge it.

2022-10-31 20:13 UTC, ctrueden commented
I have now completed (1) and (2) above. @hinerm When next you are reviewing Ops PRs, this one is ready for a look!

2022-11-16 15:48 UTC, hinerm requested changes
Overall this is looking good and the tests are great to prove that everything is working!

2022-11-16 15:48 UTC, hinerm commented on scijava/scijava-function/templates/main/java/org/scijava/function/Inplaces.vm
> +	public static InplaceInfo arityOf(Class<?> c) {
Why does `InplaceInfo#arityOf` return an `InplaceInfo` instead of an `int`, as the other two interfaces do?

2022-11-16 15:48 UTC, hinerm commented on scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/DefaultOpEnvironment.java
> +		Set<OpInfo> infos = opDirectory.values().stream().flatMap(Collection::stream).map(info -> opsFromObject(info, generators)).flatMap(Collection::stream).collect(
you should be able to just do `flatMap(Collection::stream).forEach(info -> addToOpIndex.accept(info, log));` here and skip building the set.

2022-11-16 15:48 UTC, hinerm commented on scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/reduce/FunctionReducer.java
> +		boolean canReduce = info.declaredHints().containsNone(
Why isn't this check in `ComputerReducer#canReduce`? Can the two classes extend an abstract base class to consolidate the routines? It looks like they are identical except the `xxxx.isXxxxx` and the two `arityOf` calls. So create an abstract superclass with unimplemented abstract methods delegating those three pieces?

2022-11-16 15:48 UTC, hinerm commented on scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/reduce/ReducedOpInfo.java
> +		return srcInfo().declaredHints().plus(BaseOpHints.Reduction.FORBIDDEN);
why not cache this, if necessary, in the constructor? Or lazily if you prefer?

2022-11-16 15:48 UTC, hinerm commented on scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/reduce/ReducedOpInfo.java
> +		return srcInfo.implementationName() + "Reduction" + paramsReduced;
Could a space or dash between parts of the name help here?

2022-11-16 15:48 UTC, hinerm commented on scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/reduce/ReductionUtils.java
> +//		Class<?> srcFIface = OpUtils.findFunctionalInterface(Types.raw(info.srcInfo().opType()));
remove commented out code (in a separate commit if you want to preserve the history)

2022-11-16 15:48 UTC, hinerm commented on scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/struct/OpResizingMemberParser.java
> +	 * @return a new {@link Struct} reflecting the simplified arguments / focused
We're not actually returning a `Struct` here right?

2022-11-16 15:48 UTC, hinerm commented on scijava/scijava-ops-engine/src/test/java/org/scijava/ops/engine/reduce/BiFunctionWithOptionalReducer.java
> +//package org.scijava.ops.engine.reduce;
Delete this class?

2022-11-16 15:48 UTC, hinerm commented on scijava/scijava-ops-spi/src/main/java/org/scijava/ops/spi/Optional.java
> + * this reason, it should be enforced that the annotation is only on one of the
I didn't see any negative case tests, where the annotation appears in both interface and implementation - could you add one to show what errors are produced? Or point me at it if I missed it.

2022-11-16 16:56 UTC, ctrueden commented
@hinerm Thanks so much for digging into this in detail!

Do you think it would make sense for you to take a crack at addressing your own comments, by pushing additional commits? They look relatively minor to me, and you already have your nose in it, whereas @gselzer would need to dust off his brain. Or if you don't feel comfortable making the changes yourself, maybe a pair programming session is in order?

2022-11-16 17:22 UTC, hinerm commented
>Do you think it would make sense for you to take a crack at addressing your own comments, by pushing additional commits? They look relatively minor to me, and you already have your nose in it, whereas @gselzer would need to dust off his brain. Or if you don't feel comfortable making the changes yourself, maybe a pair programming session is in order?

yep I can just make the changes @ctrueden

2022-11-17 20:47 UTC, hinerm commented on scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/DefaultOpEnvironment.java
> +		Set<OpInfo> infos = opDirectory.values().stream().flatMap(Collection::stream).map(info -> opsFromObject(info, generators)).flatMap(Collection::stream).collect(
Can't do that since we're iterating over the directory that we'll be adding to.

2022-11-18 18:07 UTC, hinerm approved these changes

2022-11-18 18:08 UTC, merged